version: "3.7"
services:
    app:
        build:
            args:
                user: nox
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: travellist
        container_name: travellist-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - travellist

    db:
        image: mysql:5.7
        container_name: travellist-db
        restart: unless-stopped
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: db
        volumes:
            - ./docker-compose/mysql:/docker-entrypoint-initdb.d
        networks:
            - travellist

    nginx:
        image: nginx:alpine
        container_name: travellist-nginx
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d/
        networks:
            - travellist

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - db:db
        ports:
            - 8080:80
        environment:
            MYSQL_USERNAME: "${DB_USERNAME}"
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
            PMA_HOST: db
        networks:
            - travellist

networks:
    travellist:
        driver: bridge
